/****Exercicio 1****/
SELECT COD_FILME, COUNT(DISTINCT DATA_RETIRADA) AS Quantidade_Aluguel
FROM LOCACOES
GROUP BY COD_FILME;

SELECT F.FILME, L.DATA_DEVOLUCAO
FROM LOCACOES L
JOIN FILME F ON L.COD_FILME = F.COD_FILME
JOIN CATEGORIA C ON F.COD_CATEGORIA = C.COD_CATEGORIA
JOIN CLIENTES CL ON L.COD_CLIENTE = CL.COD_CLIENTE
WHERE F.DIRETOR = 'Richard Donner'
AND C.NOME_CATEGORIA = 'Ação'
AND CL.NOME = 'Edson Martin Feitosa';

Select F.filme from filme F where F.diretor = 'Richard Donner'
SELECT L.DATA_DEVOLUCAO from locacoes l where l.COD_CLIENTE = 'Edson Martin Feitosa'
